from manim_lamination_builder.DepSeqList import (
    countDeploymentSequences,
    listDeploymentSequences,
    listOrbits,
)


def test_listDepSeq():
    assert listDeploymentSequences(listOrbits(3, 5), 3) == [
        "fp",
        [5, 5],
        [4, 5],
        [5, 5],
        [3, 5],
        [4, 5],
        [3, 5],
        [5, 5],
        [4, 5],
        [5, 5],
        [2, 5],
        [3, 5],
        [2, 5],
        [4, 5],
        [3, 5],
        [4, 5],
        [2, 5],
        [3, 5],
        [2, 5],
        [5, 5],
        [3, 5],
        [4, 5],
        [3, 5],
        [4, 5],
        [5, 5],
        [1, 5],
        [2, 5],
        [1, 5],
        [2, 5],
        [3, 5],
        [1, 5],
        [2, 5],
        [1, 5],
        [3, 5],
        [2, 5],
        [4, 5],
        [1, 5],
        [2, 5],
        [1, 5],
        [3, 5],
        [1, 5],
        [2, 5],
        [1, 5],
        "fp",
        [0, 5],
        [0, 5],
        [0, 5],
        [0, 5],
        [0, 5],
        [0, 5],
        "fp",
    ]


def test_countDepSeq():
    assert countDeploymentSequences(listDeploymentSequences(listOrbits(3, 5), 3)) == [
        [[5, 5], 6],
        [[4, 5], 8],
        [[3, 5], 10],
        [[2, 5], 10],
        [[1, 5], 8],
        [[0, 5], 6],
    ]
